openapi: '3.0.3'
info:
  title: "Bricks Server"
  version: 0.2.0
servers:
  - url: "http://localhost:8081"
    description: "Local Bricks Server"
paths:
  /greet:
    get:
      operationId: getGreeting
      parameters:
        - name: name
          in: query
          schema:
            type: string
      responses:
        '200':
          description: A success response with a greeting.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Greeting"
components:
  schemas:
    Greeting:
      properties:
        message:
          type: string
      required:
        - message